# Generated by Django 5.0.4 on 2024-06-19 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оценка за проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.TextField(verbose_name='О проекте'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(verbose_name='Название проекта'),
        ),
        migrations.CreateModel(
            name='UserInProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, null=True, verbose_name='Роль')),
                ('rate', models.FloatField(blank=True, default=0, null=True, verbose_name='Оценка')),
                ('text', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.userinproject')),
            ],
        ),
    ]
