# Generated by Django 5.0.4 on 2024-06-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_rating_alter_project_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberproject',
            old_name='text',
            new_name='comment',
        ),
    ]
