# Generated by Django 5.0.4 on 2024-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_text_memberproject_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О проекте'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Название проекта'),
        ),
    ]
