# Generated by Django 5.0.4 on 2024-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='users_images', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(null=True, verbose_name='Отчество'),
        ),
    ]
