# Generated by Django 5.0.4 on 2024-06-20 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(null=True, verbose_name='Институт')),
                ('trend', models.CharField(null=True, verbose_name='Направление')),
                ('course', models.SmallIntegerField(null=True, verbose_name='Курс')),
                ('bio', models.CharField(null=True, verbose_name='О себе, кратко')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
