# Generated by Django 5.0.4 on 2024-06-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_rate',
            field=models.CharField(default=0.0, null=True, verbose_name='Средняя оценка'),
        ),
    ]
